version: 0.2    

phases:
  pre_build: 
    commands:
      - echo PreBuild Started ...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 983768146132.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t tweetapp .
      - docker tag tweetapp:latest 983768146132.dkr.ecr.us-east-1.amazonaws.com/tweetapp:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 983768146132.dkr.ecr.us-east-1.amazonaws.com/tweetapp:latest
      - echo Writing definition files
      - printf '[{"name":"tweetapp","imageUri":"%s"}]'  983768146132.dkr.ecr.us-east-1.amazonaws.com/tweetapp:latest > imageDefinition.json

artifacts:
  files: 
    - imageDefinition.json